"use client";

import { useId, type ReactNode } from "react";
import { cn } from "@/lib/cn";
import { useField } from "./field";

export interface ChoiceOption<T extends string> {
  value: T;
  label: ReactNode;
  /** Secondary line (RadioCardGroup) or title tooltip (Segmented). */
  description?: string;
  icon?: ReactNode;
  disabled?: boolean;
  /** Small element at the top-right of a radio card (badge…). */
  aside?: ReactNode;
}

interface ChoiceGroupProps<T extends string> {
  value: T;
  onValueChange: (value: T) => void;
  options: ChoiceOption<T>[];
  /** Radio group name (generated by default). */
  name?: string;
  disabled?: boolean;
  /** Accessible name when not inside a `<Field group>`. */
  "aria-label"?: string;
  className?: string;
}

/**
 * Builds the radiogroup's accessible name/description from the surrounding
 * `<Field group>` when there is one.
 */
function useGroupA11y(ariaLabel: string | undefined) {
  const field = useField();
  return {
    role: "radiogroup" as const,
    "aria-label": ariaLabel,
    "aria-labelledby": ariaLabel ? undefined : field?.labelId,
    "aria-describedby": field?.describedBy,
    "aria-invalid": field?.invalid || undefined,
  };
}

export type SegmentedSize = "sm" | "md";

export interface SegmentedProps<T extends string> extends ChoiceGroupProps<T> {
  size?: SegmentedSize;
  /** Stretch segments to fill the width. */
  fullWidth?: boolean;
}

/**
 * Pill-style single choice (platform, duration, pace). Native radio inputs
 * underneath: arrow keys move the selection, Tab enters/leaves the group.
 *
 * @example
 * <Field label="Plateforme" group>
 *   <Segmented value={platform} onValueChange={setPlatform}
 *     options={SCRIPT_PLATFORMS.map((p) => ({ value: p, label: PLATFORM_LABELS[p].label }))} />
 * </Field>
 */
export function Segmented<T extends string>({
  value,
  onValueChange,
  options,
  name,
  disabled = false,
  size = "md",
  fullWidth = false,
  className,
  "aria-label": ariaLabel,
}: SegmentedProps<T>) {
  const generated = useId();
  const groupName = name ?? `${generated}-radio`;
  const a11y = useGroupA11y(ariaLabel);
  return (
    <div
      {...a11y}
      className={cn(
        "max-w-full gap-1 overflow-x-auto rounded-xl border border-line bg-surface-2 p-1 scrollbar-none",
        fullWidth ? "flex w-full" : "inline-flex",
        className,
      )}
    >
      {options.map((option) => {
        const checked = option.value === value;
        const isDisabled = disabled || option.disabled;
        return (
          <label
            key={option.value}
            title={option.description}
            className={cn(
              "relative inline-flex shrink-0 cursor-pointer select-none items-center justify-center gap-1.5 whitespace-nowrap rounded-lg font-medium",
              "transition-[background-color,color,box-shadow] duration-150 ease-out",
              "has-[:focus-visible]:outline-2 has-[:focus-visible]:outline-offset-1 has-[:focus-visible]:outline-focus",
              size === "sm" ? "h-7 px-2.5 text-xs [&_svg]:size-3.5" : "h-8 px-3 text-sm [&_svg]:size-4",
              fullWidth && "flex-1",
              checked ? "bg-surface text-ink shadow-card" : "text-muted hover:text-ink",
              isDisabled && "cursor-not-allowed opacity-50 hover:text-muted",
            )}
          >
            <input
              type="radio"
              name={groupName}
              value={option.value}
              checked={checked}
              disabled={isDisabled}
              onChange={() => onValueChange(option.value)}
              className="sr-only"
            />
            {option.icon ? <span aria-hidden className="inline-flex">{option.icon}</span> : null}
            {option.label}
          </label>
        );
      })}
    </div>
  );
}

export interface RadioCardGroupProps<T extends string> extends ChoiceGroupProps<T> {
  /** Grid columns from the `sm` breakpoint up (1 column on phones). */
  columns?: 1 | 2 | 3 | 4;
}

const gridCols: Record<NonNullable<RadioCardGroupProps<string>["columns"]>, string> = {
  1: "",
  2: "sm:grid-cols-2",
  3: "sm:grid-cols-2 lg:grid-cols-3",
  4: "sm:grid-cols-2 lg:grid-cols-4",
};

/**
 * Single choice shown as cards with a description (tone, format, hook
 * style, CTA, angle). Same keyboard model as Segmented.
 */
export function RadioCardGroup<T extends string>({
  value,
  onValueChange,
  options,
  name,
  disabled = false,
  columns = 2,
  className,
  "aria-label": ariaLabel,
}: RadioCardGroupProps<T>) {
  const generated = useId();
  const groupName = name ?? `${generated}-radio`;
  const a11y = useGroupA11y(ariaLabel);
  return (
    <div {...a11y} className={cn("grid grid-cols-1 gap-2", gridCols[columns], className)}>
      {options.map((option) => {
        const checked = option.value === value;
        const isDisabled = disabled || option.disabled;
        return (
          <label
            key={option.value}
            className={cn(
              "relative flex cursor-pointer gap-3 rounded-xl border bg-surface p-3.5 text-left",
              "transition-[border-color,background-color,box-shadow] duration-150 ease-out",
              "has-[:focus-visible]:outline-2 has-[:focus-visible]:outline-offset-2 has-[:focus-visible]:outline-focus",
              checked
                ? "border-accent bg-accent-soft/60 ring-1 ring-accent"
                : "border-line hover:border-line-strong hover:bg-surface-2",
              isDisabled && "cursor-not-allowed opacity-50 hover:border-line hover:bg-surface",
            )}
          >
            <input
              type="radio"
              name={groupName}
              value={option.value}
              checked={checked}
              disabled={isDisabled}
              onChange={() => onValueChange(option.value)}
              className="sr-only"
            />
            <span
              aria-hidden
              className={cn(
                "mt-0.5 flex size-4 shrink-0 items-center justify-center rounded-full border transition-colors duration-150",
                checked ? "border-accent bg-accent" : "border-line-strong bg-surface",
              )}
            >
              {checked ? <span className="size-1.5 rounded-full bg-accent-fg" /> : null}
            </span>
            <span className="min-w-0 flex-1">
              <span className="flex items-start justify-between gap-2">
                <span className="flex items-center gap-1.5 text-sm font-medium text-ink [&_svg]:size-4">
                  {option.icon ? <span aria-hidden className="inline-flex text-muted">{option.icon}</span> : null}
                  {option.label}
                </span>
                {option.aside}
              </span>
              {option.description ? (
                <span className="mt-0.5 block text-xs leading-relaxed text-muted">{option.description}</span>
              ) : null}
            </span>
          </label>
        );
      })}
    </div>
  );
}
